### ISSUE TITLE
Add possibility to use public IP

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [meltwater/terraform-aws-asg-dns-handler#29]
Adding this issue for visibility. We'd like to be able to set records pointing to public IP addresses of instances. 
There's PR implementing this feature: https://github.com/meltwater/terraform-aws-asg-dns-handler/pull/26

**Comment by jimsheldon** [comment]
This PR has been merged, thanks for the interest!

**Comment by jimsheldon** [comment]
Reopening this for tracking, the PR is good but our tests are broken

I'll get them fixed, update this issue, and tag a new release

**Comment by jimsheldon** [comment]
Fixed tests and published a new release https://github.com/meltwater/terraform-aws-asg-dns-handler/releases/tag/v2.1.0
