### ISSUE TITLE
Feature idea: maintain a sequence of CNAMEs per ASG

### ISSUE THREAD

**Issue by cristim** [meltwater/terraform-aws-asg-dns-handler#30]
This module looks great and we're looking into using it, thanks for the great work!

It would be nice to have a way to maintain an ordered list of CNAME records pointing to the unique records that contain the instance IDs, like in the below example for an ASG with two instances i-foo and i-bar:

When instances are added to the group, the function will create N.prefix records for each of them, as they are launched.

1.prefix -> i-foo 
2.prefix -> i-bar

Later, when maybe the instance i-foo is terminated for whatever reason, the logic would delete its CNAME record.

Once the missing instance is eventually replaced by i-baz the logic would detect the free 1.prefix and would re-create it to point to i-baz.

**Comment by jimsheldon** [comment]
Hello @cristim this is an interesting idea, but not something we have time to investigate.

We would certainly welcome a pull request adding this feature.
