### ISSUE TITLE
[Feature] Allow users to set TTL on route53 records

### ISSUE THREAD

**Issue by Infogrid-MattBuckland** [meltwater/terraform-aws-asg-dns-handler#54]
### Feature Request

Hello,

Currently the TTL set for the route53 records is hardcoded to `300s`. I would like to be able to configure this to `60s`. My use case is for a single EC2 instance in an autoscaling group with a public IP to have a static name, e.g. `web.example.com`. When the instance is replaced and the record updated I don't want to have to wait 5 minutes before being able to reconnect.

I'm happy to submit a PR for this.

### Version(s) Affected

v2.1.7

### Value Provided

Ability to customize something that otherwise is hard-coded for no apparent reason.

**Comment by bdebyl** [comment]
Hello @Infogrid-MattBuckland this has been fixed as of https://github.com/meltwater/terraform-aws-asg-dns-handler/releases/tag/v2.1.8

Let us know if you encounter any issues with this feature!
